@startuml

participant 客户企业财务编排服务 as f
participant 企业差旅服务 as t
participant 对公转账系统 as u

f -> t: 1. POST /travel-contracts/{cid}/fixd-fee
t -> u: 2. POST /union-pay/payments
u --> t
t --> f
u -> : 对接银联对公转账系统
u <-- : 客户完成支付
u -> t: 3. POST /travel-contracts/{cid}/fixd-fee/confirmation
t --> u

@enduml